#!/bin/bash
set -ex
################################################################################
##
## Bumblebee - Installer
## Copyright (c) 2016 Alces Software Ltd
##
################################################################################
BUMBLEBEEDIR="/opt/bumblebee"

# Install required dependencies
yum -y install ruby
gem install aws-sdk

git clone -b swap-networks https://github.com/alces-software/bumblebee.git $BUMBLEBEEDIR

# Set up interface configurator
cp $BUMBLEBEEDIR/dist/init/systemd/bumblebee-configurator.service /etc/systemd/system/bumblebee-configurator.service
systemctl enable bumblebee-configurator
chmod 750 $BUMBLEBEEDIR/scripts/configurator
