#!/bin/bash
set -ex
################################################################################
##
## Bumblebee - Installer
## Copyright (c) 2016 Alces Software Ltd
##
################################################################################
if [ -z $BUMBLEBEEDIR ];
then
    BUMBLEBEEDIR="/opt/bumblebee"
fi

if [ ! $(which git) ];
then
    yum -y install git
    git clone https://github.com/alces-software/bumblebee.git $BUMBLEBEEDIR
else
    git clone https://github.com/alces-software/bumblebee.git $BUMBLEBEEDIR
fi

# Set up interface configurator
cp $BUMBLEBEEDIR/dist/init/systemd/bumblebee-configurator.service /etc/systemd/system/bumblebee-configurator.service
systemctl enable bumblebee-configurator
chmod 750 $BUMBLEBEEDIR/scripts/configurator
